Add 3D demo
googlecartographer/cartographer_toyota_hsr pull request #19
Opened 2016-11-29 20:51 UTC by yutakaoka

This adds a 3D demo example. Please review it.

2016-11-29 20:57 UTC, yutakaoka commented
I signed it!

2016-11-29 21:18 UTC, macmason approved these changes

2016-11-30 09:33 UTC, damonkohler requested changes
Ideally, the VLP point clouds should be partial revolutions (e.g. one per UDP packet). That allows SLAM to unwarp them.

In a separate PR, can you add the URDF?

2016-11-30 09:33 UTC, damonkohler commented on docs/source/index.rst
> +    wget -P ~/Downloads https://s3-us-west-1.amazonaws.com/cartographer-hsr/cartographer_hsr_example_3d.bag
You should recompress this with LZ4. BZ2 is too slow for 3D data.

rosbag compress --lz4 cartographer_hsr_example_3d.bag

2016-11-30 09:33 UTC, damonkohler commented on cartographer_toyota_hsr/configuration_files/toyota_hsr_3d.lua
> +MAP_BUILDER.sparse_pose_graph.optimization_problem.huber_scale = 5e3
Did you try the backpack_3d.lua settings? They seem to work well.

I'm not suggesting you load them instead, that won't work obviously. But you may want to copy the MAP_BUILDER configuration from there.

2016-11-30 16:59 UTC, macmason commented on docs/source/index.rst
> +    wget -P ~/Downloads https://s3-us-west-1.amazonaws.com/cartographer-hsr/cartographer_hsr_example_3d.bag
#til, rosbag has lz4 support.

2016-11-30 17:25 UTC, macmason commented on docs/source/index.rst
> +    wget -P ~/Downloads https://s3-us-west-1.amazonaws.com/cartographer-hsr/cartographer_hsr_example_3d.bag
@yutakaoka I've recompressed and re-uploaded the bag. The filename is the same, but you should double-check.

@damonkohler if you'd like to host this one, send a followup PR?

2016-12-01 09:10 UTC, damonkohler commented on docs/source/index.rst
> +    wget -P ~/Downloads https://s3-us-west-1.amazonaws.com/cartographer-hsr/cartographer_hsr_example_3d.bag
I've uploaded the lz4 compressed bag here:

https://storage.googleapis.com/cartographer-public-data/bags/toyota_hsr/cartographer_toyota_hsr_demo_3d.bag

2016-12-05 21:43 UTC, yutakaoka commented on cartographer_toyota_hsr/configuration_files/toyota_hsr_3d.lua
> +MAP_BUILDER.sparse_pose_graph.optimization_problem.huber_scale = 5e3
I tried that. Both of them looked fine, but I applied your suggestion.

2016-12-05 21:43 UTC, yutakaoka commented on docs/source/index.rst
> +    wget -P ~/Downloads https://s3-us-west-1.amazonaws.com/cartographer-hsr/cartographer_hsr_example_3d.bag
Thanks, I fixed it.

2016-12-05 22:28 UTC, yutakaoka commented
Regarding the URDF, let me confirm if I can do that.

2016-12-06 07:30 UTC, damonkohler approved these changes

2016-12-06 16:50 UTC, merged